#!/bin/sh

# Stop execution on error
set -e

# Create backup and copy configuration.nix to /etc/nixos
sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.prev
sudo cp ~/.config/nixos/configuration.nix /etc/nixos/configuration.nix

# Rebuild NixOS
sudo nixos-rebuild switch

# Commit & Push to git if dotfiles are managed by git
pushd ~/.config/
if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ] ; then
	git add .
	read -p "Commit message: " commit_message
	git commit -m "NixOS Update: $commit_message"
	git push
else
	echo "Warning: dotfiles not managed by git"	
fi
popd
